### PR TITLE
Take into account search criteria when loading specific question

### PR DESCRIPTION
**Pull request by draguar**
This request aims at resolving issue #8. Search criteria are now taken into account when loading specific question. Level, complexity, tags, rules are ignored (as they have no meaning inside a unique question). When criteria can't be respected, a random permutation of the question is given
I tested with manually assigning any type of criteria, but could not test with example searchlinks in the issue, because convertSearchLinkToSettings don't seem to assign "cardsConjunc" when updating sidebarSettings, but if it did, everything should work.
Additionally, the last link supposed to give a random permutation won't. What makes it impossible to respect corresponding criteria is the level of the question, but as mentioned, this setting is ignored.

### CODE REVIEW

**Comment by KingSupernova31** [comment]
This looks wonderful, thanks. Looking over #8 again I realized there was some information missing, so I've updated the description. I think your changes still match the intended functionality, but you should confirm. I'm also a bit confused about two things you mentioned:


> could not test with example searchlinks in the issue, because convertSearchLinkToSettings don't seem to assign "cardsConjunc" when updating sidebarSettings, but if it did, everything should work.

I'm not quite sure what you mean here, I just tested and it seems to assign cardsConjunc properly. For example, [this](https://rulesguru.net/?RGYH7III1tCafjGG) link leads to a "NOT" cardsConjunc as seen [here](https://user-images.githubusercontent.com/27539004/118230237-553cbe80-b45b-11eb-8b38-8474972edfbc.JPG). Am I misunderstanding the bug?

> Additionally, the last link supposed to give a random permutation won't. What makes it impossible to respect corresponding criteria is the level of the question, but as mentioned, this setting is ignored.

Also confused about this. The last example in the previous description of #8 was a searchLink with `format=standard`, and I'm pretty sure that question doesn't have any permutations that are standard legal since suspend isn't in standard.

**Comment by draguar** [comment]
Ok thanks for the feedback, I definitely need to check back. When I tried in local, It felt like conjunction did not work but I will try again ;)
And for the last link I thought it was making the level impossible, I did not see it said format standard. I tested with manually putting format standard and it worked, so there should be no problem.

Let me see and understand why I could not get searchlinks working, then I'll modify the code if needed :)

**Comment by draguar** [comment]
The Conjunc problem was my fault: a problem in my regex match with the url. Its been corrected. Also updated the branch by merging your new commits. Everything is up-to-date and seem to work as intended (manual criteria modifications or searchlinks). 
I simply notice that the second link in the issue has a searchlink not starting with RG. Is this possible ? I manually generated another searchlink with same criteria for testing.

**Comment by KingSupernova31** [comment]
> I simply notice that the second link in the issue has a searchlink not starting with RG. Is this possible ?

Whoops, no, that was a typo. Sorry about that. Fixed.

**Pull request merged**
